name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest  # Roda numa máquina Linux na nuvem

    steps:
    # 1. Baixa o seu código
    - name: Checkout do código
      uses: actions/checkout@v4

    # 2. Instala o Python 3.11
    - name: Configurar Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    # 3. Instala as dependências (Django, Pylint, Black, etc)
    - name: Instalar Dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint black

    # 4. Verifica se o código está formatado (Black)
    - name: Checar Formatação (Black)
      run: |
        black --check .

    # 5. Roda o Pylint (Se a nota cair, ele avisa!)
    - name: Analisar Qualidade (Pylint)
      run: |
        pylint store

    # 6. Roda os Testes (Manage.py test)
    - name: Rodar Testes Automatizados
      run: |
        python manage.py test